### PR TITLE
Fixed Windows build script for VS versions other than Community

### PR DESCRIPTION
**Pull request by LukeMaycock**

### CODE REVIEW

**Comment by LukeMaycock** [comment]
Unfortunately that path doesn't work for the Professional Edition, which uses "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe".

The changes to all the install paths in 2017 seem to be a bit of a mess at the moment!

**Comment by drowaudio** [comment]
Yeah. I'm not quite sure what I can do here. I think more people will have "Community" installed but "Professional" users are unlikely to have this. "BuildTools" is a separate download so could be used with both but I'm not sure if it's common to have that as well as "Community" or "Professional"?

**Comment by drowaudio** [comment]
I've made this optional now, if you specify the `MSBUILD_EXE` variable before running the script, it will use that path, otherwise it will default to the community edition one.
I hope that helps.

**Comment by LukeMaycock** [comment]
That sounds like a good solution to me! Thanks for that.

**Pull request closed without merging**
