### PR TITLE
Bump JUCE to develop (post 7.0.5) for VST host fix

### PR DESCRIPTION
**Pull request by sudara**

### CODE REVIEW

**Comment by drowaudio** [comment]
This is failing the CI for me now when testing the juce example VST3 plugins.
I’m guessing that’s because they’re now VST3 bundles? Did it pass on your CI?

**Comment by sudara** [comment]
Sorry, I opened the PR before tests wrapped on my fork. Didn’t expect the merge, was going to add something to changlists and bump version to 1.0.3, I can take a look tomorrow!

**Comment by sudara** [comment]
Looks like all platforms are failing (segfault) right after `Starting tests in: pluginval / Listing available buses...`

Possibly related: https://forum.juce.com/t/crash-juce-vst3-linux-cant-pass-pluginval/54927?u=sudara

I'm not able to verify locally, because #101 and #102 make pluginval consume 100% CPU and stall on my current plugin, perhaps due to the fact I have many hundreds of parameters and setState is now being called once per param.

**Comment by sudara** [comment]
Ok, tried another plugin, couldn't reproduce locally. Have to move on for now, but I can look into the JUCE examples next.  Feel free to revert if you want develop happy.

**Comment by sudara** [comment]
Seems like it might be choking on `listBuses (ut, instance, false)` — on all platforms the `true` version seems to produce its output and then it bails.

**Comment by sudara** [comment]
K, did my homework to repro locally https://forum.juce.com/t/juce-7-vst2-and-pluginval-testing-crashes/54905/15?u=sudara

**Comment by drowaudio** [comment]
Ok, so it looks like it's a juce bug and we'll just have to wait for it to get fixed there?

**Comment by sudara** [comment]
Seems that way! If a resolution doesn't seem imminent I can look into a workaround.

**Pull request merged**
