### PR TITLE
feat: Add option to pass file with disabled tests

### PR DESCRIPTION
**Pull request by abrykt**

### CODE REVIEW

**Comment by drowaudio** [comment]
Before I add this, can I ask what the use case is? Is there a reason you need to disable specific tests rather than just use a lower testing level?

**Comment by abrykt** [comment]
The plugins that we are testing involves hardware, and to be able to run the test "Plugin state restoration" we need to have the hardware connected because the hardware is the only piece that can parse the binary blob. We would like to be able to run the test suite also when the hardware is not connected, and with the option to pass a file with disabled tests we can disable the test that we know will fail without the hardware connected, and have it enabled when we run the tests with the hardware connected.

**Comment by abrykt** [comment]
I can also imagine it is useful during development when you don't have everything implemented, but some tests are running successfully. With this in place you can enable the test in CI, one by one in a TDD style.

**Comment by drowaudio** [comment]
Ok, I've added this here: https://github.com/Tracktion/pluginval/commit/cc41f87fdf44582bf906305a51c5d1bf2f414976

**Pull request closed without merging**
